-- Material You colorscheme for Neovim generated by matugen

local colors = {
	-- Base surfaces
	bg = "#1a120d",
	bg_dim = "#1a120d",
	bg_bright = "#413732",

	-- Container surfaces (for UI elements)
	bg_container_lowest = "#140d08",
	bg_container_low = "#221a15",
	bg_container = "#271e19",
	bg_container_high = "#312823",
	bg_container_highest = "#3d332e",

	-- Text colors
	fg = "#f0dfd7",
	fg_variant = "#d7c2b9",

	-- Primary colors
	primary = "#ffb68e",
	on_primary = "#532200",
	primary_container = "#6f3813",
	on_primary_container = "#ffdbc9",
	primary_fixed = "#ffdbc9",
	primary_fixed_dim = "#ffb68e",

	-- Secondary colors
	secondary = "#e6beaa",
	on_secondary = "#432b1d",
	secondary_container = "#5c4132",
	on_secondary_container = "#ffdbc9",
	secondary_fixed = "#ffdbc9",
	secondary_fixed_dim = "#e6beaa",

	-- Tertiary colors
	tertiary = "#cdc991",
	on_tertiary = "#343208",
	tertiary_container = "#4b481d",
	on_tertiary_container = "#eae5ab",
	tertiary_fixed = "#eae5ab",
	tertiary_fixed_dim = "#cdc991",

	-- Error colors
	error = "#ffb4ab",
	on_error = "#690005",
	error_container = "#93000a",
	on_error_container = "#ffdad6",

	-- Other UI elements
	outline = "#9f8d84",
	outline_variant = "#52443c",
	shadow = "#000000",
	scrim = "#000000",

	-- Inverse colors
	inverse_surface = "#f0dfd7",
	inverse_on_surface = "#382e29",
	inverse_primary = "#8c4e28",
}

-- Clear existing highlights
vim.cmd("highlight clear")
if vim.g.syntax_on then
	vim.cmd("syntax reset")
end

vim.g.colors_name = "material-you"
vim.o.termguicolors = true
vim.o.background = "dark" -- or "light" depending on your preference

-- UI elements
vim.api.nvim_set_hl(0, "Normal", { fg = colors.fg, bg = colors.bg })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = colors.fg, bg = colors.bg_container })
vim.api.nvim_set_hl(0, "NormalNC", { fg = colors.fg_variant, bg = colors.bg_dim })
vim.api.nvim_set_hl(0, "Cursor", { fg = colors.bg, bg = colors.primary })
vim.api.nvim_set_hl(0, "CursorLine", { bg = colors.bg_container_low })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = colors.bg_container_low })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = colors.bg_container })
vim.api.nvim_set_hl(0, "LineNr", { fg = colors.fg_variant })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = colors.primary, bold = true })
vim.api.nvim_set_hl(0, "SignColumn", { bg = colors.bg })
vim.api.nvim_set_hl(0, "VertSplit", { fg = colors.outline })
vim.api.nvim_set_hl(0, "StatusLine", { fg = colors.fg, bg = colors.bg_container_high })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = colors.fg_variant, bg = colors.bg_container })
vim.api.nvim_set_hl(0, "Pmenu", { fg = colors.fg, bg = colors.bg_container })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = colors.on_primary, bg = colors.primary })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = colors.bg_container_high })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = colors.primary })
vim.api.nvim_set_hl(0, "Search", { fg = colors.on_secondary_container, bg = colors.secondary_container })
vim.api.nvim_set_hl(0, "IncSearch", { fg = colors.on_tertiary_container, bg = colors.tertiary_container })
vim.api.nvim_set_hl(0, "MatchParen", { fg = colors.tertiary, bold = true, underline = true })
vim.api.nvim_set_hl(0, "Visual", { bg = colors.primary_container })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = colors.bg_container_high })
vim.api.nvim_set_hl(0, "Folded", { fg = colors.fg_variant, bg = colors.bg_container })
vim.api.nvim_set_hl(0, "FoldColumn", { fg = colors.fg_variant, bg = colors.bg })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = colors.tertiary, bg = colors.bg_container })
vim.api.nvim_set_hl(0, "DiffChange", { fg = colors.secondary, bg = colors.bg_container })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = colors.error, bg = colors.bg_container })
vim.api.nvim_set_hl(0, "DiffText", { fg = colors.primary, bg = colors.bg_container })
vim.api.nvim_set_hl(0, "Directory", { fg = colors.primary })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = colors.error })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = colors.tertiary }) -- Using tertiary as warning
vim.api.nvim_set_hl(0, "ModeMsg", { fg = colors.fg, bold = true })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = colors.primary })
vim.api.nvim_set_hl(0, "Question", { fg = colors.primary })
vim.api.nvim_set_hl(0, "NonText", { fg = colors.fg_variant })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "Title", { fg = colors.primary, bold = true })
vim.api.nvim_set_hl(0, "WildMenu", { fg = colors.on_primary, bg = colors.primary })

-- Syntax highlighting
vim.api.nvim_set_hl(0, "Comment", { fg = colors.fg_variant, italic = true })
vim.api.nvim_set_hl(0, "Constant", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "String", { fg = colors.secondary })
vim.api.nvim_set_hl(0, "Character", { fg = colors.secondary })
vim.api.nvim_set_hl(0, "Number", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "Boolean", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "Float", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "Identifier", { fg = colors.fg })
vim.api.nvim_set_hl(0, "Function", { fg = colors.primary })
vim.api.nvim_set_hl(0, "Statement", { fg = colors.primary })
vim.api.nvim_set_hl(0, "Conditional", { fg = colors.primary })
vim.api.nvim_set_hl(0, "Repeat", { fg = colors.primary })
vim.api.nvim_set_hl(0, "Label", { fg = colors.primary })
vim.api.nvim_set_hl(0, "Operator", { fg = colors.primary })
vim.api.nvim_set_hl(0, "Keyword", { fg = colors.primary })
vim.api.nvim_set_hl(0, "Exception", { fg = colors.error })
vim.api.nvim_set_hl(0, "PreProc", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "Include", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "Define", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "Macro", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "PreCondit", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "Type", { fg = colors.secondary })
vim.api.nvim_set_hl(0, "StorageClass", { fg = colors.secondary })
vim.api.nvim_set_hl(0, "Structure", { fg = colors.secondary })
vim.api.nvim_set_hl(0, "Typedef", { fg = colors.secondary })
vim.api.nvim_set_hl(0, "Special", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "Tag", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "Delimiter", { fg = colors.fg })
vim.api.nvim_set_hl(0, "SpecialComment", { fg = colors.fg_variant, italic = true })
vim.api.nvim_set_hl(0, "Debug", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "Underlined", { fg = colors.primary, underline = true })
vim.api.nvim_set_hl(0, "Ignore", { fg = colors.fg_variant })
vim.api.nvim_set_hl(0, "Error", { fg = colors.error })
vim.api.nvim_set_hl(0, "Todo", { fg = colors.bg, bg = colors.tertiary, bold = true })

-- Diagnostics
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = colors.error })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = colors.tertiary }) -- Using tertiary for warnings
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = colors.secondary }) -- Using secondary for info
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = colors.primary })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = colors.error })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = colors.tertiary })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = colors.secondary })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = colors.primary })

-- Treesitter
vim.api.nvim_set_hl(0, "@variable", { fg = colors.fg })
vim.api.nvim_set_hl(0, "@function", { fg = colors.primary })
vim.api.nvim_set_hl(0, "@function.builtin", { fg = colors.primary })
vim.api.nvim_set_hl(0, "@keyword", { fg = colors.primary })
vim.api.nvim_set_hl(0, "@string", { fg = colors.secondary })
vim.api.nvim_set_hl(0, "@number", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "@boolean", { fg = colors.tertiary })
vim.api.nvim_set_hl(0, "@type", { fg = colors.secondary })
vim.api.nvim_set_hl(0, "@property", { fg = colors.fg })
vim.api.nvim_set_hl(0, "@field", { fg = colors.fg })
vim.api.nvim_set_hl(0, "@parameter", { fg = colors.fg, italic = true })
vim.api.nvim_set_hl(0, "@comment", { fg = colors.fg_variant, italic = true })
vim.api.nvim_set_hl(0, "@operator", { fg = colors.primary })
vim.api.nvim_set_hl(0, "@punctuation.delimiter", { fg = colors.fg })
vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = colors.fg })
vim.api.nvim_set_hl(0, "@tag", { fg = colors.primary })
vim.api.nvim_set_hl(0, "@tag.attribute", { fg = colors.secondary })
vim.api.nvim_set_hl(0, "@tag.delimiter", { fg = colors.fg })

-- LSP
vim.api.nvim_set_hl(0, "LspReferenceText", { bg = colors.bg_container_high })
vim.api.nvim_set_hl(0, "LspReferenceRead", { bg = colors.bg_container_high })
vim.api.nvim_set_hl(0, "LspReferenceWrite", { bg = colors.bg_container_high })

-- Return the colors table for use in other plugins
return colors
