-- Material You colorscheme for Neovim
-- Generated by matugen

-- Load the matugen module which has the theme setup
local ok, matugen = pcall(require, "matugen")
if not ok then
  vim.notify("Failed to load matugen module", vim.log.levels.ERROR)
  return
end

-- The module will automatically set up the colorscheme