-- Material You colorscheme for Neovim generated by matugen
local colors = {
	-- Base surfaces
	bg = "#101510",
	bg_dim = "#101510",
	bg_bright = "#353a35",

	-- Container surfaces (for UI elements)
	bg_container_lowest = "#0b0f0b",
	bg_container_low = "#181d18",
	bg_container = "#1c211c",
	bg_container_high = "#262b26",
	bg_container_highest = "#313631",

	-- Text colors
	fg = "#dfe4dc",
	fg_variant = "#c1c9bf",

	-- Primary colors
	primary = "#99d4a3",
	on_primary = "#003919",
	primary_container = "#17512b",
	on_primary_container = "#b4f1be",
	primary_fixed = "#b4f1be",
	primary_fixed_dim = "#99d4a3",

	-- Secondary colors
	secondary = "#b7ccb7",
	on_secondary = "#233426",
	secondary_container = "#394b3b",
	on_secondary_container = "#d3e8d2",
	secondary_fixed = "#d3e8d2",
	secondary_fixed_dim = "#b7ccb7",

	-- Tertiary colors
	tertiary = "#a2ced8",
	on_tertiary = "#01363e",
	tertiary_container = "#204d56",
	on_tertiary_container = "#bdeaf5",
	tertiary_fixed = "#bdeaf5",
	tertiary_fixed_dim = "#a2ced8",

	-- Error colors
	error = "#ffb4ab",
	on_error = "#690005",
	error_container = "#93000a",
	on_error_container = "#ffdad6",

	-- Other UI elements
	outline = "#8b938a",
	outline_variant = "#414941",
	shadow = "#000000",
	scrim = "#000000",

	-- Inverse colors
	inverse_surface = "#dfe4dc",
	inverse_on_surface = "#2d322c",
	inverse_primary = "#326941",
}

-- Return the colors table for use in other plugins
return colors
